### ISSUE TITLE
Feature: Create missing attribute options

### ISSUE THREAD

**Issue by schmengler** [firegento/FireGento_ExtendedImport2#1]

**Comment by ponyfleisch** [comment]
Are you working on this? I'm trying to do this in my own extension and am hitting a couple of roadblocks.

**Comment by EliasKotlyar** [comment]
Hello ponyfleisch,

for now i cannot tell you whats the current state about the development of this feature. 

Can you please explain which roadblocks you are hitting?

I made a task list for this feature:

As far as i see, we need first to write an integration test,which will do the following:
1. Check if a test-attribute is avaible,and delete it 
2. create a test-attribute with some options assigned to it 
3. test if a certain option is present(should fail)
4. import data for a testproduct with the a new option
5. test if a certain option is present(should sucess)
6. clean up(remove the attribute etc)

After that we will have a good development enviroment for this feature.

Then we will have to look around Line 1543 in Magento\CatalogImportExport\Model\Import\Product:
// 6. Attributes phase

We will need to implement some plugin which will loop trough the bunches and check if all options are present. If not it should append them. 

Greetings
Elias

**Comment by ponyfleisch** [comment]
Currently i'm inserting the new options inside _getNextRow() of my Class that extends `Magento\ImportExport\Model\Import\AbstractSource`.

The available options are cached though (`\Magento\CatalogImportExport\Model\Import\Product\Type\AbstractType::$commonAttributesCache` and _attributes of its instances) and cause the validation of the row to fail.

If i do two passes, it works as expected.

**Comment by EliasKotlyar** [comment]
Hello everyone,

I implemented this Feature and merged it to the master branch. Can someone please devtest it?

Greetings
Elias

**Comment by amenk** [comment]
AFAIR it is working :)
