### ISSUE TITLE
Custom Attribute Option not created

### ISSUE THREAD

**Issue by mage2sol** [firegento/FireGento_ExtendedImport2#14]
I have recently try your extension and getting error like below in ajax.

<b>Fatal error</b>:  Uncaught Error: Call to a member function getValue() on null in magento_root/app/code/FireGento/ExtendedImport/Plugin/CreateMissingAttributeOptionPlugin.php:109
Stack trace:

**Comment by mage2sol** [comment]
any update?

**Comment by EliasZ** [comment]
probably related to #12

**Comment by VincentMarmiesse** [comment]
Hello,
I have the same issue on a Magento 2.2.2 with the last version of FireGento_ExtendedImport2 and FireGento_FastSimpleImport2.

Do you know if something changed in 2.2.2?

**Comment by EliasKotlyar** [comment]
Hello @VincentMarmiesse ,

Do you use the actual development version from master branch? It should be fixxed there.

**Comment by VincentMarmiesse** [comment]
Hi @EliasKotlyar,

Yes I think so, I am using Composer and here is my `composer.json`

```
...
"require": {
   ...
   "firegento/extendedimport": "dev-master"
},
...
"repositories": {
   ...
   "firegento_extendedimport2": {
      "type": "vcs",
      "url": "https://github.com/firegento/FireGento_ExtendedImport2"
   }
}
```
  
EDIT : FYI I have the same issue as #12, not exactly the Fatal error.

**Comment by iunctim** [comment]
Still not working. Having the same problem... :-/

**Comment by Henry7901** [comment]
Still not working. Having exactly the same problem :-/
When will it be fixed?

**Comment by mage2sol** [comment]
Thanks it is solved
