### ISSUE TITLE
Release versioning and packagist

### ISSUE THREAD

**Issue by tdgroot** [firegento/FireGento_ExtendedImport2#18]
It'd be nice if the module had release versioning, so I don't have to install `dev-master`. Also, the package is missing on Packagist. 

These two things seem intentional on Firegento's side, what's the thought of doing it the way it's currently going?

**Comment by EliasKotlyar** [comment]
Hello @tdgroot ,

I have unfortunately no access to the Firegento-Packagist-Account. I will ask about who is having access to it.

Greatings
Elias

**Comment by danslo** [comment]
@EliasKotlyar Regardless of packagist (we can do it later), could you tag this repository? So at least we can use it in projects without having to lower stability or use commit hashes. Thanks a lot!

**Comment by VincentMarmiesse** [comment]
+1, thanks!

**Comment by amenk** [comment]
*bump*

**Comment by amenk** [comment]
anybody? :D

**Comment by fredden** [comment]
@sprankhub can you help with this, please?

**Comment by sprankhub** [comment]
We do have tagged releases now: https://github.com/firegento/FireGento_ExtendedImport2/releases

So the only thing missing here is to submit it to packagist.org, right @fredden?

**Comment by fredden** [comment]
Thanks for tagging the recent release(s). Yes, I think this just needs to be submitted to Packagist to close out this issue now. Sorry to nag! Meanwhile we've discovered we're able to install this via Private Packagist.

**Comment by sprankhub** [comment]
No worries, @fredden. Here you go: https://packagist.org/packages/firegento/extendedimport
