### ISSUE TITLE
Feature: Improved Error Messages on Attribute Validation

### ISSUE THREAD

**Issue by schmengler** [firegento/FireGento_ExtendedImport2#2]
Use improved validation messages as in Avs_FastSimpleImport

**Comment by EliasKotlyar** [comment]
Hello Fabian,

How is the state of this feature?

Greetings
Elias

**Comment by schmengler** [comment]
For invalid attribute types the error messages are implemented and I didn't have the chance yet to continue working on the project. I guess this issue can be closed, and if additional error messages should be included, it's a new task.
