### ISSUE TITLE
Custom Attribute Option not created part 2

### ISSUE THREAD

**Issue by Detzler** [firegento/FireGento_ExtendedImport2#20]
There is a condition implemented 3 months ago which allows creating attribute options on thy fly as long as the attribute source model is an instance of Magento\Eav\Model\Entity\Attribute\Source\Table:

https://github.com/firegento/FireGento_ExtendedImport2/blame/master/Plugin/CreateMissingAttributeOptionPlugin.php#L48

When I create a select attribute via backend the attribute receives the mentioned source model.

The problem is that any other select attributes, which has been created via Setup, don't contain any source model. The field is just NULL. Take a look at the color attribute which comes from magento's setup.

So is it just that simple to extend the condition with "is empty" for the source model value?

**Comment by Detzler** [comment]
When I create a multiselect attribute via backend the source model is empty too

**Comment by amenk** [comment]
I just discovered that on-the-fly generation also does not work for me for multi-select attributes. 
Is there any progress on this? @Detzler Where you able to debug that down? Any PullRequest in the making?
