### ISSUE TITLE
Unknown module(s): 'FireGento/ExtendedImport'

### ISSUE THREAD

**Issue by freeaed** [firegento/FireGento_ExtendedImport2#22]
I try to make installation , and I get this error

**Comment by elburro1887** [comment]
you need to use a "_" not a "\\", there is a typo in the docs:

`bin/magento module:enable FireGento_ExtendedImport`

**Comment by sprankhub** [comment]
Docs fixed in https://github.com/firegento/FireGento_ExtendedImport2/commit/66f168841eda11947ec988db65eef1ae49270b5d.
