### ISSUE TITLE
Create missing attribute oprions, source_model is not working for multiselect attributes

### ISSUE THREAD

**Issue by cfroe** [firegento/FireGento_ExtendedImport2#27]
The CreateMissingAttributeOptionPlugin.php is working fine for "Dropdown Attributes", when I have a "Multiselect Attribute" the "source_model" is null, so attributes aren't created. In lines 48-50 the function returns without creating attributes if the source_model is not 'Magento\Eav\Model\Entity\Attribute\Source\Table'

`$attribute = $this->eavConfig->getAttribute('catalog_product', $attrCode);
        if ($attribute->getSourceModel() != 'Magento\Eav\Model\Entity\Attribute\Source\Table') {
            return array($attrCode, $attrParams, $rowData);
        }`

I'm using Magento 2.2.5. If I comment the lines out everything is working fine

**Comment by DanieliMi** [comment]
How can this be fixed?

**Comment by DanieliMi** [comment]
Related with #20 which has a open PR ?

**Comment by cfroe** [comment]
Hi DanieliMi, I'm not a real Magento Developer, so I just use the dirty hack to comment the lines out and everything is working.
