### ISSUE TITLE
Feature: Allow importing _links_related_sku in one line via separator  

### ISSUE THREAD

**Issue by amenk** [firegento/FireGento_ExtendedImport2#29]
If I understand the Magento standard import correctly, multiple link SKUs have to be imported as one-SKU per line.

In some cases it is not easy to create such CSV files. It would be better to also support multiple SKUs per line, separated with the separation character, for example `|`such as  `SKU1|SKU2|SKU3`

Would you merge such a feature? 
Should it made as additional config option or just work out of the box (I think it does no harm)

**Comment by EliasKotlyar** [comment]
sure :)

**Comment by EliasKotlyar** [comment]
I think it can work out of the box, because its not harming the rest of the functionality at all

**Comment by amenk** [comment]
The core does this already -- at least in 2.3.1 (and I think already earlier)

\Magento\CatalogImportExport\Model\Import\Product::_saveLinks

                        $linkSkus = explode($this->getMultipleValueSeparator(), $rowData[$linkName . 'sku']);


nevermind...
