### ISSUE TITLE
Feature: Allow setting attributes to empty in "Add/Update" mode

### ISSUE THREAD

**Issue by schmengler** [firegento/FireGento_ExtendedImport2#3]
by default empty columns are ignored.

**Comment by EliasKotlyar** [comment]
This feature will be included in near Future in the module FastSimpleImport2.

**Comment by sylvainraye** [comment]
It's a magento 2 issue. There is an issue about it https://github.com/magento/magento2/issues/7468 and https://github.com/magento/magento2/issues/10006

**Comment by sprankhub** [comment]
AFAIK, this is now possible in Magento core. See https://github.com/magento/magento2/pull/13472.
