### ISSUE TITLE
how to import product attributes

### ISSUE THREAD

**Issue by sharmavartika** [firegento/FireGento_ExtendedImport2#36]
is there any example which shows how to import product attributes like this?
$productsArray = [
    [
        'sku' => 'firegento-test',
        'attribute_set_code' => 'Default',
        'product_type' => 'simple',
        'product_websites' => 'base',
        'name' => 'FireGento Test Product',
        'price' => '14.0000',
    ],
];

**Comment by ortoDev** [comment]
`
$data[] = array(
            'sku' => $record["sku"],
            'product_type' => 'simple',
            'attribute_set_code' => $record["attribute_set_code"],
            'product_websites' => "base",
            'categories' => $record["categories"],
            'name' => $record["name"],
            'is_in_stock' => $record["is_in_stock"],
            'brand'             => $record["brand"] //this is a custom attribute
        );

$importerModel = $objectManager->create('FireGento\FastSimpleImport\Model\Importer');
$importerModel->setEntityCode('catalog_product');
$importerModel->processImport($data);
`

**Comment by papanada** [comment]
@vartikaongraph
```
$data[] = array(
            'sku' => $record["sku"],
            'product_type' => "simple",
            'product_websites' => "base",
            'brand'             => $record["brand"],
        );

$importerModel = $objectManager->create('FireGento\FastSimpleImport\Model\Importer');
$importerModel->setEntityCode('catalog_product');
$importerModel->processImport($data);
```
