### ISSUE TITLE
Feature: Category import

### ISSUE THREAD

**Issue by schmengler** [firegento/FireGento_ExtendedImport2#5]

**Comment by Marc-Falconer** [comment]
Sorry this is probably a stupid question. But is there an example of how to import Categories?

Would you put the data in an array in a php file then run it?

Thanks for your help.

**Comment by EliasKotlyar** [comment]
Hello kiwi-777,

Unfortunately this feature is not implemented yet. Feel free to contribute and submit a solution trough a pull-request.

Greetings
Elias

**Comment by amenk** [comment]
I might be wrong, but that seems to work nowadays?
https://github.com/firegento/FireGento_FastSimpleImport2_Demo/blob/master/Console/Command/Category/ImportCategory.php

**Comment by sprankhub** [comment]
Yes, this has been implemented in `FireGento_FastSimpleImport2`, see https://github.com/firegento/FireGento_FastSimpleImport2/blob/711b7f1d5b2a57083973bb73dd94d698fded34f1/etc/import.xml#L9.
