### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by jameswithers** [firegento/FireGento_ExtendedImport2#6]
On installation, when doing `bin/magento setup:upgrade` I get the error:

```
[Magento\Framework\Exception\LocalizedException]
  Invalid XML in file /app/code/FireGento/ExtendedImport/etc/events.xml:
  Element 'config': Missing child element(s). Expected is ( event ).
  Line: 2
```

Removing `etc/events.xml` solves the problem

**Comment by EliasKotlyar** [comment]
Hello jameswithers,

Many thanks for your contribution. We removed the unnecessary events.xml.

Greetings
Elias
